include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/build/"
    - "**/generated/"

language:
  strict-casts: true
  strict-inference: true
  strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_specify_types
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_field_initializers_in_const_classes
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_type_to_string
    - avoid_slow_async_io
    - avoid_void_async
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - eol_at_end_of_file
    - implicit_reopen
    - join_return_with_assignment
    - lines_longer_than_80_chars
    - matching_super_parameters
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_single_quotes
    - prefer_relative_imports
    - prefer_void_to_null
    - require_trailing_commas
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - super_goes_last
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_final
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unreachable_from_main
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    - use_truncating_division
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
